---
matrix:
  include:
    - BASE: unstable-slim
      TAGS: '[ "unstable" ]'
    - BASE: trixie-slim
      TAGS: '[ "trixie", "1.4" ]'
    - BASE: bookworm-slim
      TAGS: '[ "bookworm", "1.2", "latest" ]'

variables:
  - &build-settings
    repo: nold360/borgserver,ghcr.io/nold360/borgserver
    tags: ${TAGS}
    platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
    build_args:
      BASE_IMAGE: debian:${BASE}

steps:
  - name: test-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dry-run: true
      <<: *build-settings
    when:
      - event: [manual, push]
        branch: 
          exclude: [ master ]

  - name: build-and-release
    image: woodpeckerci/plugin-docker-buildx
    settings:
      <<: *build-settings
      logins:
        - registry: https://index.docker.io/v1/
          username: 
            from_secret: docker_username
          password:
            from_secret: docker_password

        - registry: https://ghcr.io/v1/
          repo: ghcr.io/nold360/borgserver
          username: 
            from_secret: docker_username
          password:
            from_secret: gh_push_token
    when:
      - branch: master
        event: [cron, manual, push]
