---
variables:
  - &kaniko_plugin 'plugins/kaniko:1.6'

matrix:
  include:
    - BASE: trixie-slim
      TAGS: '[ "trixie", "1.4" ]'
    - BASE: bookworm-slim
      TAGS: '[ "bookworm", "1.2", "latest" ]'

steps:
  - name: build
    image: *kaniko_plugin
    settings:
      repo: nold360/borgserver
      dockerfile: Dockerfile
      build_args:
        - BASE_IMAGE=debian:${BASE}
      tags: ${TAGS}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      - branch: master
      - event: cron
