---
matrix:
  include:
    - BASE: unstable-slim
      TAGS: '[ "unstable" ]'
    - BASE: trixie-slim
      TAGS: '[ "trixie", "1.4" ]'
    - BASE: bookworm-slim
      TAGS: '[ "bookworm", "1.2", "latest" ]'

steps:
  publish-release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: nold360/borgserver
      platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
      registry: docker.io
      tags: ${TAGS}
      build_args:
        - BASE_IMAGE=debian:${BASE}
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
